package iso639

var (
	isocodes3 = map[string]ISOEntry{
		"AAR": {
			alph3b: "AAR",
			alph3t: "XXX",
			alph2:  "AA",
			enName: "Afar",
			frName: "afar",
		},
		"ABK": {
			alph3b: "ABK",
			alph3t: "XXX",
			alph2:  "AB",
			enName: "Abkhazian",
			frName: "abkhaze",
		},
		"ACE": {
			alph3b: "ACE",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Achinese",
			frName: "aceh",
		},
		"ACH": {
			alph3b: "ACH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Acoli",
			frName: "acoli",
		},
		"ADA": {
			alph3b: "ADA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Adangme",
			frName: "adangme",
		},
		"ADY": {
			alph3b: "ADY",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Adyghe; Adygei",
			frName: "adyghé",
		},
		"AFA": {
			alph3b: "AFA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Afro-Asiatic languages",
			frName: "afro-asiatiques, langues",
		},
		"AFH": {
			alph3b: "AFH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Afrihili",
			frName: "afrihili",
		},
		"AFR": {
			alph3b: "AFR",
			alph3t: "XXX",
			alph2:  "AF",
			enName: "Afrikaans",
			frName: "afrikaans",
		},
		"AIN": {
			alph3b: "AIN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Ainu",
			frName: "aïnou",
		},
		"AKA": {
			alph3b: "AKA",
			alph3t: "XXX",
			alph2:  "AK",
			enName: "Akan",
			frName: "akan",
		},
		"AKK": {
			alph3b: "AKK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Akkadian",
			frName: "akkadien",
		},
		"ALB": {
			alph3b: "ALB",
			alph3t: "SQI",
			alph2:  "SQ",
			enName: "Albanian",
			frName: "albanais",
		},
		"ALE": {
			alph3b: "ALE",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Aleut",
			frName: "aléoute",
		},
		"ALG": {
			alph3b: "ALG",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Algonquian languages",
			frName: "algonquines, langues",
		},
		"ALT": {
			alph3b: "ALT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Southern Altai",
			frName: "altai du Sud",
		},
		"AMH": {
			alph3b: "AMH",
			alph3t: "XXX",
			alph2:  "AM",
			enName: "Amharic",
			frName: "amharique",
		},
		"ANG": {
			alph3b: "ANG",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "English, Old (ca.450-1100)",
			frName: "anglo-saxon (ca.450-1100)",
		},
		"ANP": {
			alph3b: "ANP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Angika",
			frName: "angika",
		},
		"APA": {
			alph3b: "APA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Apache languages",
			frName: "apaches, langues",
		},
		"ARA": {
			alph3b: "ARA",
			alph3t: "XXX",
			alph2:  "AR",
			enName: "Arabic",
			frName: "arabe",
		},
		"ARC": {
			alph3b: "ARC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)",
			frName: "araméen d'empire (700-300 BCE)",
		},
		"ARG": {
			alph3b: "ARG",
			alph3t: "XXX",
			alph2:  "AN",
			enName: "Aragonese",
			frName: "aragonais",
		},
		"ARM": {
			alph3b: "ARM",
			alph3t: "HYE",
			alph2:  "HY",
			enName: "Armenian",
			frName: "arménien",
		},
		"ARN": {
			alph3b: "ARN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mapudungun; Mapuche",
			frName: "mapudungun; mapuche; mapuce",
		},
		"ARP": {
			alph3b: "ARP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Arapaho",
			frName: "arapaho",
		},
		"ART": {
			alph3b: "ART",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Artificial languages",
			frName: "artificielles, langues",
		},
		"ARW": {
			alph3b: "ARW",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Arawak",
			frName: "arawak",
		},
		"ASM": {
			alph3b: "ASM",
			alph3t: "XXX",
			alph2:  "AS",
			enName: "Assamese",
			frName: "assamais",
		},
		"AST": {
			alph3b: "AST",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Asturian; Bable; Leonese; Asturleonese",
			frName: "asturien; bable; léonais; asturoléonais",
		},
		"ATH": {
			alph3b: "ATH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Athapascan languages",
			frName: "athapascanes, langues",
		},
		"AUS": {
			alph3b: "AUS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Australian languages",
			frName: "australiennes, langues",
		},
		"AVA": {
			alph3b: "AVA",
			alph3t: "XXX",
			alph2:  "AV",
			enName: "Avaric",
			frName: "avar",
		},
		"AVE": {
			alph3b: "AVE",
			alph3t: "XXX",
			alph2:  "AE",
			enName: "Avestan",
			frName: "avestique",
		},
		"AWA": {
			alph3b: "AWA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Awadhi",
			frName: "awadhi",
		},
		"AYM": {
			alph3b: "AYM",
			alph3t: "XXX",
			alph2:  "AY",
			enName: "Aymara",
			frName: "aymara",
		},
		"AZE": {
			alph3b: "AZE",
			alph3t: "XXX",
			alph2:  "AZ",
			enName: "Azerbaijani",
			frName: "azéri",
		},
		"BAD": {
			alph3b: "BAD",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Banda languages",
			frName: "banda, langues",
		},
		"BAI": {
			alph3b: "BAI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Bamileke languages",
			frName: "bamiléké, langues",
		},
		"BAK": {
			alph3b: "BAK",
			alph3t: "XXX",
			alph2:  "BA",
			enName: "Bashkir",
			frName: "bachkir",
		},
		"BAL": {
			alph3b: "BAL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Baluchi",
			frName: "baloutchi",
		},
		"BAM": {
			alph3b: "BAM",
			alph3t: "XXX",
			alph2:  "BM",
			enName: "Bambara",
			frName: "bambara",
		},
		"BAN": {
			alph3b: "BAN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Balinese",
			frName: "balinais",
		},
		"BAQ": {
			alph3b: "BAQ",
			alph3t: "EUS",
			alph2:  "EU",
			enName: "Basque",
			frName: "basque",
		},
		"BAS": {
			alph3b: "BAS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Basa",
			frName: "basa",
		},
		"BAT": {
			alph3b: "BAT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Baltic languages",
			frName: "baltes, langues",
		},
		"BEJ": {
			alph3b: "BEJ",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Beja; Bedawiyet",
			frName: "bedja",
		},
		"BEL": {
			alph3b: "BEL",
			alph3t: "XXX",
			alph2:  "BE",
			enName: "Belarusian",
			frName: "biélorusse",
		},
		"BEM": {
			alph3b: "BEM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Bemba",
			frName: "bemba",
		},
		"BEN": {
			alph3b: "BEN",
			alph3t: "XXX",
			alph2:  "BN",
			enName: "Bengali",
			frName: "bengali",
		},
		"BER": {
			alph3b: "BER",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Berber languages",
			frName: "berbères, langues",
		},
		"BHO": {
			alph3b: "BHO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Bhojpuri",
			frName: "bhojpuri",
		},
		"BIH": {
			alph3b: "BIH",
			alph3t: "XXX",
			alph2:  "BH",
			enName: "Bihari languages",
			frName: "langues biharis",
		},
		"BIK": {
			alph3b: "BIK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Bikol",
			frName: "bikol",
		},
		"BIN": {
			alph3b: "BIN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Bini; Edo",
			frName: "bini; edo",
		},
		"BIS": {
			alph3b: "BIS",
			alph3t: "XXX",
			alph2:  "BI",
			enName: "Bislama",
			frName: "bichlamar",
		},
		"BLA": {
			alph3b: "BLA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Siksika",
			frName: "blackfoot",
		},
		"BNT": {
			alph3b: "BNT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Bantu languages",
			frName: "bantou, langues",
		},
		"BOS": {
			alph3b: "BOS",
			alph3t: "XXX",
			alph2:  "BS",
			enName: "Bosnian",
			frName: "bosniaque",
		},
		"BRA": {
			alph3b: "BRA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Braj",
			frName: "braj",
		},
		"BRE": {
			alph3b: "BRE",
			alph3t: "XXX",
			alph2:  "BR",
			enName: "Breton",
			frName: "breton",
		},
		"BTK": {
			alph3b: "BTK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Batak languages",
			frName: "batak, langues",
		},
		"BUA": {
			alph3b: "BUA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Buriat",
			frName: "bouriate",
		},
		"BUG": {
			alph3b: "BUG",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Buginese",
			frName: "bugi",
		},
		"BUL": {
			alph3b: "BUL",
			alph3t: "XXX",
			alph2:  "BG",
			enName: "Bulgarian",
			frName: "bulgare",
		},
		"BUR": {
			alph3b: "BUR",
			alph3t: "MYA",
			alph2:  "MY",
			enName: "Burmese",
			frName: "birman",
		},
		"BYN": {
			alph3b: "BYN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Blin; Bilin",
			frName: "blin; bilen",
		},
		"CAD": {
			alph3b: "CAD",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Caddo",
			frName: "caddo",
		},
		"CAI": {
			alph3b: "CAI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Central American Indian languages",
			frName: "amérindiennes de L'Amérique centrale, langues",
		},
		"CAR": {
			alph3b: "CAR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Galibi Carib",
			frName: "karib; galibi; carib",
		},
		"CAT": {
			alph3b: "CAT",
			alph3t: "XXX",
			alph2:  "CA",
			enName: "Catalan; Valencian",
			frName: "catalan; valencien",
		},
		"CAU": {
			alph3b: "CAU",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Caucasian languages",
			frName: "caucasiennes, langues",
		},
		"CEB": {
			alph3b: "CEB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Cebuano",
			frName: "cebuano",
		},
		"CEL": {
			alph3b: "CEL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Celtic languages",
			frName: "celtiques, langues; celtes, langues",
		},
		"CHA": {
			alph3b: "CHA",
			alph3t: "XXX",
			alph2:  "CH",
			enName: "Chamorro",
			frName: "chamorro",
		},
		"CHB": {
			alph3b: "CHB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Chibcha",
			frName: "chibcha",
		},
		"CHE": {
			alph3b: "CHE",
			alph3t: "XXX",
			alph2:  "CE",
			enName: "Chechen",
			frName: "tchétchène",
		},
		"CHG": {
			alph3b: "CHG",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Chagatai",
			frName: "djaghataï",
		},
		"CHI": {
			alph3b: "CHI",
			alph3t: "ZHO",
			alph2:  "ZH",
			enName: "Chinese",
			frName: "chinois",
		},
		"CHK": {
			alph3b: "CHK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Chuukese",
			frName: "chuuk",
		},
		"CHM": {
			alph3b: "CHM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mari",
			frName: "mari",
		},
		"CHN": {
			alph3b: "CHN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Chinook jargon",
			frName: "chinook, jargon",
		},
		"CHO": {
			alph3b: "CHO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Choctaw",
			frName: "choctaw",
		},
		"CHP": {
			alph3b: "CHP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Chipewyan; Dene Suline",
			frName: "chipewyan",
		},
		"CHR": {
			alph3b: "CHR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Cherokee",
			frName: "cherokee",
		},
		"CHU": {
			alph3b: "CHU",
			alph3t: "XXX",
			alph2:  "CU",
			enName: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
			frName: "slavon d'église; vieux slave; slavon liturgique; vieux bulgare",
		},
		"CHV": {
			alph3b: "CHV",
			alph3t: "XXX",
			alph2:  "CV",
			enName: "Chuvash",
			frName: "tchouvache",
		},
		"CHY": {
			alph3b: "CHY",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Cheyenne",
			frName: "cheyenne",
		},
		"CMC": {
			alph3b: "CMC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Chamic languages",
			frName: "chames, langues",
		},
		"CNR": {
			alph3b: "CNR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Montenegrin",
			frName: "monténégrin",
		},
		"COP": {
			alph3b: "COP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Coptic",
			frName: "copte",
		},
		"COR": {
			alph3b: "COR",
			alph3t: "XXX",
			alph2:  "KW",
			enName: "Cornish",
			frName: "cornique",
		},
		"COS": {
			alph3b: "COS",
			alph3t: "XXX",
			alph2:  "CO",
			enName: "Corsican",
			frName: "corse",
		},
		"CPE": {
			alph3b: "CPE",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Creoles and pidgins, English based",
			frName: "créoles et pidgins basés sur l'anglais",
		},
		"CPF": {
			alph3b: "CPF",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Creoles and pidgins, French-based",
			frName: "créoles et pidgins basés sur le français",
		},
		"CPP": {
			alph3b: "CPP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Creoles and pidgins, Portuguese-based",
			frName: "créoles et pidgins basés sur le portugais",
		},
		"CRE": {
			alph3b: "CRE",
			alph3t: "XXX",
			alph2:  "CR",
			enName: "Cree",
			frName: "cree",
		},
		"CRH": {
			alph3b: "CRH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Crimean Tatar; Crimean Turkish",
			frName: "tatar de Crimé",
		},
		"CRP": {
			alph3b: "CRP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Creoles and pidgins",
			frName: "créoles et pidgins",
		},
		"CSB": {
			alph3b: "CSB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kashubian",
			frName: "kachoube",
		},
		"CUS": {
			alph3b: "CUS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Cushitic languages",
			frName: "couchitiques, langues",
		},
		"CZE": {
			alph3b: "CZE",
			alph3t: "CES",
			alph2:  "CS",
			enName: "Czech",
			frName: "tchèque",
		},
		"DAK": {
			alph3b: "DAK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Dakota",
			frName: "dakota",
		},
		"DAN": {
			alph3b: "DAN",
			alph3t: "XXX",
			alph2:  "DA",
			enName: "Danish",
			frName: "danois",
		},
		"DAR": {
			alph3b: "DAR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Dargwa",
			frName: "dargwa",
		},
		"DAY": {
			alph3b: "DAY",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Land Dayak languages",
			frName: "dayak, langues",
		},
		"DEL": {
			alph3b: "DEL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Delaware",
			frName: "delaware",
		},
		"DEN": {
			alph3b: "DEN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Slave (Athapascan)",
			frName: "esclave (athapascan)",
		},
		"DGR": {
			alph3b: "DGR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Dogrib",
			frName: "dogrib",
		},
		"DIN": {
			alph3b: "DIN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Dinka",
			frName: "dinka",
		},
		"DIV": {
			alph3b: "DIV",
			alph3t: "XXX",
			alph2:  "DV",
			enName: "Divehi; Dhivehi; Maldivian",
			frName: "maldivien",
		},
		"DOI": {
			alph3b: "DOI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Dogri",
			frName: "dogri",
		},
		"DRA": {
			alph3b: "DRA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Dravidian languages",
			frName: "dravidiennes, langues",
		},
		"DSB": {
			alph3b: "DSB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Lower Sorbian",
			frName: "bas-sorabe",
		},
		"DUA": {
			alph3b: "DUA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Duala",
			frName: "douala",
		},
		"DUM": {
			alph3b: "DUM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Dutch, Middle (ca.1050-1350)",
			frName: "néerlandais moyen (ca. 1050-1350)",
		},
		"DUT": {
			alph3b: "DUT",
			alph3t: "NLD",
			alph2:  "NL",
			enName: "Dutch; Flemish",
			frName: "néerlandais; flamand",
		},
		"DYU": {
			alph3b: "DYU",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Dyula",
			frName: "dioula",
		},
		"DZO": {
			alph3b: "DZO",
			alph3t: "XXX",
			alph2:  "DZ",
			enName: "Dzongkha",
			frName: "dzongkha",
		},
		"EFI": {
			alph3b: "EFI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Efik",
			frName: "efik",
		},
		"EGY": {
			alph3b: "EGY",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Egyptian (Ancient)",
			frName: "égyptien",
		},
		"EKA": {
			alph3b: "EKA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Ekajuk",
			frName: "ekajuk",
		},
		"ELX": {
			alph3b: "ELX",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Elamite",
			frName: "élamite",
		},
		"ENG": {
			alph3b: "ENG",
			alph3t: "XXX",
			alph2:  "EN",
			enName: "English",
			frName: "anglais",
		},
		"ENM": {
			alph3b: "ENM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "English, Middle (1100-1500)",
			frName: "anglais moyen (1100-1500)",
		},
		"EPO": {
			alph3b: "EPO",
			alph3t: "XXX",
			alph2:  "EO",
			enName: "Esperanto",
			frName: "espéranto",
		},
		"EST": {
			alph3b: "EST",
			alph3t: "XXX",
			alph2:  "ET",
			enName: "Estonian",
			frName: "estonien",
		},
		"EWE": {
			alph3b: "EWE",
			alph3t: "XXX",
			alph2:  "EE",
			enName: "Ewe",
			frName: "éwé",
		},
		"EWO": {
			alph3b: "EWO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Ewondo",
			frName: "éwondo",
		},
		"FAN": {
			alph3b: "FAN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Fang",
			frName: "fang",
		},
		"FAO": {
			alph3b: "FAO",
			alph3t: "XXX",
			alph2:  "FO",
			enName: "Faroese",
			frName: "féroïen",
		},
		"FAT": {
			alph3b: "FAT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Fanti",
			frName: "fanti",
		},
		"FIJ": {
			alph3b: "FIJ",
			alph3t: "XXX",
			alph2:  "FJ",
			enName: "Fijian",
			frName: "fidjien",
		},
		"FIL": {
			alph3b: "FIL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Filipino; Pilipino",
			frName: "filipino; pilipino",
		},
		"FIN": {
			alph3b: "FIN",
			alph3t: "XXX",
			alph2:  "FI",
			enName: "Finnish",
			frName: "finnois",
		},
		"FIU": {
			alph3b: "FIU",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Finno-Ugrian languages",
			frName: "finno-ougriennes, langues",
		},
		"FON": {
			alph3b: "FON",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Fon",
			frName: "fon",
		},
		"FRE": {
			alph3b: "FRE",
			alph3t: "FRA",
			alph2:  "FR",
			enName: "French",
			frName: "français",
		},
		"FRM": {
			alph3b: "FRM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "French, Middle (ca.1400-1600)",
			frName: "français moyen (1400-1600)",
		},
		"FRO": {
			alph3b: "FRO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "French, Old (842-ca.1400)",
			frName: "français ancien (842-ca.1400)",
		},
		"FRR": {
			alph3b: "FRR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Northern Frisian",
			frName: "frison septentrional",
		},
		"FRS": {
			alph3b: "FRS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Eastern Frisian",
			frName: "frison oriental",
		},
		"FRY": {
			alph3b: "FRY",
			alph3t: "XXX",
			alph2:  "FY",
			enName: "Western Frisian",
			frName: "frison occidental",
		},
		"FUL": {
			alph3b: "FUL",
			alph3t: "XXX",
			alph2:  "FF",
			enName: "Fulah",
			frName: "peul",
		},
		"FUR": {
			alph3b: "FUR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Friulian",
			frName: "frioulan",
		},
		"GAA": {
			alph3b: "GAA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Ga",
			frName: "ga",
		},
		"GAY": {
			alph3b: "GAY",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Gayo",
			frName: "gayo",
		},
		"GBA": {
			alph3b: "GBA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Gbaya",
			frName: "gbaya",
		},
		"GEM": {
			alph3b: "GEM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Germanic languages",
			frName: "germaniques, langues",
		},
		"GEO": {
			alph3b: "GEO",
			alph3t: "KAT",
			alph2:  "KA",
			enName: "Georgian",
			frName: "géorgien",
		},
		"GER": {
			alph3b: "GER",
			alph3t: "DEU",
			alph2:  "DE",
			enName: "German",
			frName: "allemand",
		},
		"GEZ": {
			alph3b: "GEZ",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Geez",
			frName: "guèze",
		},
		"GIL": {
			alph3b: "GIL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Gilbertese",
			frName: "kiribati",
		},
		"GLA": {
			alph3b: "GLA",
			alph3t: "XXX",
			alph2:  "GD",
			enName: "Gaelic; Scottish Gaelic",
			frName: "gaélique; gaélique écossais",
		},
		"GLE": {
			alph3b: "GLE",
			alph3t: "XXX",
			alph2:  "GA",
			enName: "Irish",
			frName: "irlandais",
		},
		"GLG": {
			alph3b: "GLG",
			alph3t: "XXX",
			alph2:  "GL",
			enName: "Galician",
			frName: "galicien",
		},
		"GLV": {
			alph3b: "GLV",
			alph3t: "XXX",
			alph2:  "GV",
			enName: "Manx",
			frName: "manx; mannois",
		},
		"GMH": {
			alph3b: "GMH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "German, Middle High (ca.1050-1500)",
			frName: "allemand, moyen haut (ca. 1050-1500)",
		},
		"GOH": {
			alph3b: "GOH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "German, Old High (ca.750-1050)",
			frName: "allemand, vieux haut (ca. 750-1050)",
		},
		"GON": {
			alph3b: "GON",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Gondi",
			frName: "gond",
		},
		"GOR": {
			alph3b: "GOR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Gorontalo",
			frName: "gorontalo",
		},
		"GOT": {
			alph3b: "GOT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Gothic",
			frName: "gothique",
		},
		"GRB": {
			alph3b: "GRB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Grebo",
			frName: "grebo",
		},
		"GRC": {
			alph3b: "GRC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Greek, Ancient (to 1453)",
			frName: "grec ancien (jusqu'à 1453)",
		},
		"GRE": {
			alph3b: "GRE",
			alph3t: "ELL",
			alph2:  "EL",
			enName: "Greek, Modern (1453-)",
			frName: "grec moderne (après 1453)",
		},
		"GRN": {
			alph3b: "GRN",
			alph3t: "XXX",
			alph2:  "GN",
			enName: "Guarani",
			frName: "guarani",
		},
		"GSW": {
			alph3b: "GSW",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Swiss German; Alemannic; Alsatian",
			frName: "suisse alémanique; alémanique; alsacien",
		},
		"GUJ": {
			alph3b: "GUJ",
			alph3t: "XXX",
			alph2:  "GU",
			enName: "Gujarati",
			frName: "goudjrati",
		},
		"GWI": {
			alph3b: "GWI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Gwich'in",
			frName: "gwich'in",
		},
		"HAI": {
			alph3b: "HAI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Haida",
			frName: "haida",
		},
		"HAT": {
			alph3b: "HAT",
			alph3t: "XXX",
			alph2:  "HT",
			enName: "Haitian; Haitian Creole",
			frName: "haïtien; créole haïtien",
		},
		"HAU": {
			alph3b: "HAU",
			alph3t: "XXX",
			alph2:  "HA",
			enName: "Hausa",
			frName: "haoussa",
		},
		"HAW": {
			alph3b: "HAW",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Hawaiian",
			frName: "hawaïen",
		},
		"HEB": {
			alph3b: "HEB",
			alph3t: "XXX",
			alph2:  "HE",
			enName: "Hebrew",
			frName: "hébreu",
		},
		"HER": {
			alph3b: "HER",
			alph3t: "XXX",
			alph2:  "HZ",
			enName: "Herero",
			frName: "herero",
		},
		"HIL": {
			alph3b: "HIL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Hiligaynon",
			frName: "hiligaynon",
		},
		"HIM": {
			alph3b: "HIM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Himachali languages; Western Pahari languages",
			frName: "langues himachalis; langues paharis occidentales",
		},
		"HIN": {
			alph3b: "HIN",
			alph3t: "XXX",
			alph2:  "HI",
			enName: "Hindi",
			frName: "hindi",
		},
		"HIT": {
			alph3b: "HIT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Hittite",
			frName: "hittite",
		},
		"HMN": {
			alph3b: "HMN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Hmong; Mong",
			frName: "hmong",
		},
		"HMO": {
			alph3b: "HMO",
			alph3t: "XXX",
			alph2:  "HO",
			enName: "Hiri Motu",
			frName: "hiri motu",
		},
		"HRV": {
			alph3b: "HRV",
			alph3t: "XXX",
			alph2:  "HR",
			enName: "Croatian",
			frName: "croate",
		},
		"HSB": {
			alph3b: "HSB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Upper Sorbian",
			frName: "haut-sorabe",
		},
		"HUN": {
			alph3b: "HUN",
			alph3t: "XXX",
			alph2:  "HU",
			enName: "Hungarian",
			frName: "hongrois",
		},
		"HUP": {
			alph3b: "HUP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Hupa",
			frName: "hupa",
		},
		"IBA": {
			alph3b: "IBA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Iban",
			frName: "iban",
		},
		"IBO": {
			alph3b: "IBO",
			alph3t: "XXX",
			alph2:  "IG",
			enName: "Igbo",
			frName: "igbo",
		},
		"ICE": {
			alph3b: "ICE",
			alph3t: "ISL",
			alph2:  "IS",
			enName: "Icelandic",
			frName: "islandais",
		},
		"IDO": {
			alph3b: "IDO",
			alph3t: "XXX",
			alph2:  "IO",
			enName: "Ido",
			frName: "ido",
		},
		"III": {
			alph3b: "III",
			alph3t: "XXX",
			alph2:  "II",
			enName: "Sichuan Yi; Nuosu",
			frName: "yi de Sichuan",
		},
		"IJO": {
			alph3b: "IJO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Ijo languages",
			frName: "ijo, langues",
		},
		"IKU": {
			alph3b: "IKU",
			alph3t: "XXX",
			alph2:  "IU",
			enName: "Inuktitut",
			frName: "inuktitut",
		},
		"ILE": {
			alph3b: "ILE",
			alph3t: "XXX",
			alph2:  "IE",
			enName: "Interlingue; Occidental",
			frName: "interlingue",
		},
		"ILO": {
			alph3b: "ILO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Iloko",
			frName: "ilocano",
		},
		"INA": {
			alph3b: "INA",
			alph3t: "XXX",
			alph2:  "IA",
			enName: "Interlingua (International Auxiliary Language Association)",
			frName: "interlingua (langue auxiliaire internationale)",
		},
		"INC": {
			alph3b: "INC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Indic languages",
			frName: "indo-aryennes, langues",
		},
		"IND": {
			alph3b: "IND",
			alph3t: "XXX",
			alph2:  "ID",
			enName: "Indonesian",
			frName: "indonésien",
		},
		"INE": {
			alph3b: "INE",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Indo-European languages",
			frName: "indo-européennes, langues",
		},
		"INH": {
			alph3b: "INH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Ingush",
			frName: "ingouche",
		},
		"IPK": {
			alph3b: "IPK",
			alph3t: "XXX",
			alph2:  "IK",
			enName: "Inupiaq",
			frName: "inupiaq",
		},
		"IRA": {
			alph3b: "IRA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Iranian languages",
			frName: "iraniennes, langues",
		},
		"IRO": {
			alph3b: "IRO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Iroquoian languages",
			frName: "iroquoises, langues",
		},
		"ITA": {
			alph3b: "ITA",
			alph3t: "XXX",
			alph2:  "IT",
			enName: "Italian",
			frName: "italien",
		},
		"JAV": {
			alph3b: "JAV",
			alph3t: "XXX",
			alph2:  "JV",
			enName: "Javanese",
			frName: "javanais",
		},
		"JBO": {
			alph3b: "JBO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Lojban",
			frName: "lojban",
		},
		"JPN": {
			alph3b: "JPN",
			alph3t: "XXX",
			alph2:  "JA",
			enName: "Japanese",
			frName: "japonais",
		},
		"JPR": {
			alph3b: "JPR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Judeo-Persian",
			frName: "judéo-persan",
		},
		"JRB": {
			alph3b: "JRB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Judeo-Arabic",
			frName: "judéo-arabe",
		},
		"KAA": {
			alph3b: "KAA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kara-Kalpak",
			frName: "karakalpak",
		},
		"KAB": {
			alph3b: "KAB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kabyle",
			frName: "kabyle",
		},
		"KAC": {
			alph3b: "KAC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kachin; Jingpho",
			frName: "kachin; jingpho",
		},
		"KAL": {
			alph3b: "KAL",
			alph3t: "XXX",
			alph2:  "KL",
			enName: "Kalaallisut; Greenlandic",
			frName: "groenlandais",
		},
		"KAM": {
			alph3b: "KAM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kamba",
			frName: "kamba",
		},
		"KAN": {
			alph3b: "KAN",
			alph3t: "XXX",
			alph2:  "KN",
			enName: "Kannada",
			frName: "kannada",
		},
		"KAR": {
			alph3b: "KAR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Karen languages",
			frName: "karen, langues",
		},
		"KAS": {
			alph3b: "KAS",
			alph3t: "XXX",
			alph2:  "KS",
			enName: "Kashmiri",
			frName: "kashmiri",
		},
		"KAU": {
			alph3b: "KAU",
			alph3t: "XXX",
			alph2:  "KR",
			enName: "Kanuri",
			frName: "kanouri",
		},
		"KAW": {
			alph3b: "KAW",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kawi",
			frName: "kawi",
		},
		"KAZ": {
			alph3b: "KAZ",
			alph3t: "XXX",
			alph2:  "KK",
			enName: "Kazakh",
			frName: "kazakh",
		},
		"KBD": {
			alph3b: "KBD",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kabardian",
			frName: "kabardien",
		},
		"KHA": {
			alph3b: "KHA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Khasi",
			frName: "khasi",
		},
		"KHI": {
			alph3b: "KHI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Khoisan languages",
			frName: "khoïsan, langues",
		},
		"KHM": {
			alph3b: "KHM",
			alph3t: "XXX",
			alph2:  "KM",
			enName: "Central Khmer",
			frName: "khmer central",
		},
		"KHO": {
			alph3b: "KHO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Khotanese; Sakan",
			frName: "khotanais; sakan",
		},
		"KIK": {
			alph3b: "KIK",
			alph3t: "XXX",
			alph2:  "KI",
			enName: "Kikuyu; Gikuyu",
			frName: "kikuyu",
		},
		"KIN": {
			alph3b: "KIN",
			alph3t: "XXX",
			alph2:  "RW",
			enName: "Kinyarwanda",
			frName: "rwanda",
		},
		"KIR": {
			alph3b: "KIR",
			alph3t: "XXX",
			alph2:  "KY",
			enName: "Kirghiz; Kyrgyz",
			frName: "kirghiz",
		},
		"KMB": {
			alph3b: "KMB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kimbundu",
			frName: "kimbundu",
		},
		"KOK": {
			alph3b: "KOK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Konkani",
			frName: "konkani",
		},
		"KOM": {
			alph3b: "KOM",
			alph3t: "XXX",
			alph2:  "KV",
			enName: "Komi",
			frName: "kom",
		},
		"KON": {
			alph3b: "KON",
			alph3t: "XXX",
			alph2:  "KG",
			enName: "Kongo",
			frName: "kongo",
		},
		"KOR": {
			alph3b: "KOR",
			alph3t: "XXX",
			alph2:  "KO",
			enName: "Korean",
			frName: "coréen",
		},
		"KOS": {
			alph3b: "KOS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kosraean",
			frName: "kosrae",
		},
		"KPE": {
			alph3b: "KPE",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kpelle",
			frName: "kpellé",
		},
		"KRC": {
			alph3b: "KRC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Karachay-Balkar",
			frName: "karatchai balkar",
		},
		"KRL": {
			alph3b: "KRL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Karelian",
			frName: "carélien",
		},
		"KRO": {
			alph3b: "KRO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kru languages",
			frName: "krou, langues",
		},
		"KRU": {
			alph3b: "KRU",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kurukh",
			frName: "kurukh",
		},
		"KUA": {
			alph3b: "KUA",
			alph3t: "XXX",
			alph2:  "KJ",
			enName: "Kuanyama; Kwanyama",
			frName: "kuanyama; kwanyama",
		},
		"KUM": {
			alph3b: "KUM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kumyk",
			frName: "koumyk",
		},
		"KUR": {
			alph3b: "KUR",
			alph3t: "XXX",
			alph2:  "KU",
			enName: "Kurdish",
			frName: "kurde",
		},
		"KUT": {
			alph3b: "KUT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kutenai",
			frName: "kutenai",
		},
		"LAD": {
			alph3b: "LAD",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Ladino",
			frName: "judéo-espagnol",
		},
		"LAH": {
			alph3b: "LAH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Lahnda",
			frName: "lahnda",
		},
		"LAM": {
			alph3b: "LAM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Lamba",
			frName: "lamba",
		},
		"LAO": {
			alph3b: "LAO",
			alph3t: "XXX",
			alph2:  "LO",
			enName: "Lao",
			frName: "lao",
		},
		"LAT": {
			alph3b: "LAT",
			alph3t: "XXX",
			alph2:  "LA",
			enName: "Latin",
			frName: "latin",
		},
		"LAV": {
			alph3b: "LAV",
			alph3t: "XXX",
			alph2:  "LV",
			enName: "Latvian",
			frName: "letton",
		},
		"LEZ": {
			alph3b: "LEZ",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Lezghian",
			frName: "lezghien",
		},
		"LIM": {
			alph3b: "LIM",
			alph3t: "XXX",
			alph2:  "LI",
			enName: "Limburgan; Limburger; Limburgish",
			frName: "limbourgeois",
		},
		"LIN": {
			alph3b: "LIN",
			alph3t: "XXX",
			alph2:  "LN",
			enName: "Lingala",
			frName: "lingala",
		},
		"LIT": {
			alph3b: "LIT",
			alph3t: "XXX",
			alph2:  "LT",
			enName: "Lithuanian",
			frName: "lituanien",
		},
		"LOL": {
			alph3b: "LOL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mongo",
			frName: "mongo",
		},
		"LOZ": {
			alph3b: "LOZ",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Lozi",
			frName: "lozi",
		},
		"LTZ": {
			alph3b: "LTZ",
			alph3t: "XXX",
			alph2:  "LB",
			enName: "Luxembourgish; Letzeburgesch",
			frName: "luxembourgeois",
		},
		"LUA": {
			alph3b: "LUA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Luba-Lulua",
			frName: "luba-lulua",
		},
		"LUB": {
			alph3b: "LUB",
			alph3t: "XXX",
			alph2:  "LU",
			enName: "Luba-Katanga",
			frName: "luba-katanga",
		},
		"LUG": {
			alph3b: "LUG",
			alph3t: "XXX",
			alph2:  "LG",
			enName: "Ganda",
			frName: "ganda",
		},
		"LUI": {
			alph3b: "LUI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Luiseno",
			frName: "luiseno",
		},
		"LUN": {
			alph3b: "LUN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Lunda",
			frName: "lunda",
		},
		"LUO": {
			alph3b: "LUO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Luo (Kenya and Tanzania)",
			frName: "luo (Kenya et Tanzanie)",
		},
		"LUS": {
			alph3b: "LUS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Lushai",
			frName: "lushai",
		},
		"MAC": {
			alph3b: "MAC",
			alph3t: "MKD",
			alph2:  "MK",
			enName: "Macedonian",
			frName: "macédonien",
		},
		"MAD": {
			alph3b: "MAD",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Madurese",
			frName: "madourais",
		},
		"MAG": {
			alph3b: "MAG",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Magahi",
			frName: "magahi",
		},
		"MAH": {
			alph3b: "MAH",
			alph3t: "XXX",
			alph2:  "MH",
			enName: "Marshallese",
			frName: "marshall",
		},
		"MAI": {
			alph3b: "MAI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Maithili",
			frName: "maithili",
		},
		"MAK": {
			alph3b: "MAK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Makasar",
			frName: "makassar",
		},
		"MAL": {
			alph3b: "MAL",
			alph3t: "XXX",
			alph2:  "ML",
			enName: "Malayalam",
			frName: "malayalam",
		},
		"MAN": {
			alph3b: "MAN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mandingo",
			frName: "mandingue",
		},
		"MAO": {
			alph3b: "MAO",
			alph3t: "MRI",
			alph2:  "MI",
			enName: "Maori",
			frName: "maori",
		},
		"MAP": {
			alph3b: "MAP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Austronesian languages",
			frName: "austronésiennes, langues",
		},
		"MAR": {
			alph3b: "MAR",
			alph3t: "XXX",
			alph2:  "MR",
			enName: "Marathi",
			frName: "marathe",
		},
		"MAS": {
			alph3b: "MAS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Masai",
			frName: "massaï",
		},
		"MAY": {
			alph3b: "MAY",
			alph3t: "MSA",
			alph2:  "MS",
			enName: "Malay",
			frName: "malais",
		},
		"MDF": {
			alph3b: "MDF",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Moksha",
			frName: "moksa",
		},
		"MDR": {
			alph3b: "MDR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mandar",
			frName: "mandar",
		},
		"MEN": {
			alph3b: "MEN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mende",
			frName: "mendé",
		},
		"MGA": {
			alph3b: "MGA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Irish, Middle (900-1200)",
			frName: "irlandais moyen (900-1200)",
		},
		"MIC": {
			alph3b: "MIC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mi'kmaq; Micmac",
			frName: "mi'kmaq; micmac",
		},
		"MIN": {
			alph3b: "MIN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Minangkabau",
			frName: "minangkabau",
		},
		"MIS": {
			alph3b: "MIS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Uncoded languages",
			frName: "langues non codées",
		},
		"MKH": {
			alph3b: "MKH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mon-Khmer languages",
			frName: "môn-khmer, langues",
		},
		"MLG": {
			alph3b: "MLG",
			alph3t: "XXX",
			alph2:  "MG",
			enName: "Malagasy",
			frName: "malgache",
		},
		"MLT": {
			alph3b: "MLT",
			alph3t: "XXX",
			alph2:  "MT",
			enName: "Maltese",
			frName: "maltais",
		},
		"MNC": {
			alph3b: "MNC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Manchu",
			frName: "mandchou",
		},
		"MNI": {
			alph3b: "MNI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Manipuri",
			frName: "manipuri",
		},
		"MNO": {
			alph3b: "MNO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Manobo languages",
			frName: "manobo, langues",
		},
		"MOH": {
			alph3b: "MOH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mohawk",
			frName: "mohawk",
		},
		"MON": {
			alph3b: "MON",
			alph3t: "XXX",
			alph2:  "MN",
			enName: "Mongolian",
			frName: "mongol",
		},
		"MOS": {
			alph3b: "MOS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mossi",
			frName: "moré",
		},
		"MUL": {
			alph3b: "MUL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Multiple languages",
			frName: "multilingue",
		},
		"MUN": {
			alph3b: "MUN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Munda languages",
			frName: "mounda, langues",
		},
		"MUS": {
			alph3b: "MUS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Creek",
			frName: "muskogee",
		},
		"MWL": {
			alph3b: "MWL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mirandese",
			frName: "mirandais",
		},
		"MWR": {
			alph3b: "MWR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Marwari",
			frName: "marvari",
		},
		"MYN": {
			alph3b: "MYN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Mayan languages",
			frName: "maya, langues",
		},
		"MYV": {
			alph3b: "MYV",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Erzya",
			frName: "erza",
		},
		"NAH": {
			alph3b: "NAH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Nahuatl languages",
			frName: "nahuatl, langues",
		},
		"NAI": {
			alph3b: "NAI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "North American Indian languages",
			frName: "nord-amérindiennes, langues",
		},
		"NAP": {
			alph3b: "NAP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Neapolitan",
			frName: "napolitain",
		},
		"NAU": {
			alph3b: "NAU",
			alph3t: "XXX",
			alph2:  "NA",
			enName: "Nauru",
			frName: "nauruan",
		},
		"NAV": {
			alph3b: "NAV",
			alph3t: "XXX",
			alph2:  "NV",
			enName: "Navajo; Navaho",
			frName: "navaho",
		},
		"NBL": {
			alph3b: "NBL",
			alph3t: "XXX",
			alph2:  "NR",
			enName: "Ndebele, South; South Ndebele",
			frName: "ndébélé du Sud",
		},
		"NDE": {
			alph3b: "NDE",
			alph3t: "XXX",
			alph2:  "ND",
			enName: "Ndebele, North; North Ndebele",
			frName: "ndébélé du Nord",
		},
		"NDO": {
			alph3b: "NDO",
			alph3t: "XXX",
			alph2:  "NG",
			enName: "Ndonga",
			frName: "ndonga",
		},
		"NDS": {
			alph3b: "NDS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Low German; Low Saxon; German, Low; Saxon, Low",
			frName: "bas allemand; bas saxon; allemand, bas; saxon, bas",
		},
		"NEP": {
			alph3b: "NEP",
			alph3t: "XXX",
			alph2:  "NE",
			enName: "Nepali",
			frName: "népalais",
		},
		"NEW": {
			alph3b: "NEW",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Nepal Bhasa; Newari",
			frName: "nepal bhasa; newari",
		},
		"NIA": {
			alph3b: "NIA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Nias",
			frName: "nias",
		},
		"NIC": {
			alph3b: "NIC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Niger-Kordofanian languages",
			frName: "nigéro-kordofaniennes, langues",
		},
		"NIU": {
			alph3b: "NIU",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Niuean",
			frName: "niué",
		},
		"NNO": {
			alph3b: "NNO",
			alph3t: "XXX",
			alph2:  "NN",
			enName: "Norwegian Nynorsk; Nynorsk, Norwegian",
			frName: "norvégien nynorsk; nynorsk, norvégien",
		},
		"NOB": {
			alph3b: "NOB",
			alph3t: "XXX",
			alph2:  "NB",
			enName: "Bokmål, Norwegian; Norwegian Bokmål",
			frName: "norvégien bokmål",
		},
		"NOG": {
			alph3b: "NOG",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Nogai",
			frName: "nogaï; nogay",
		},
		"NON": {
			alph3b: "NON",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Norse, Old",
			frName: "norrois, vieux",
		},
		"NOR": {
			alph3b: "NOR",
			alph3t: "XXX",
			alph2:  "NO",
			enName: "Norwegian",
			frName: "norvégien",
		},
		"NQO": {
			alph3b: "NQO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "N'Ko",
			frName: "n'ko",
		},
		"NSO": {
			alph3b: "NSO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Pedi; Sepedi; Northern Sotho",
			frName: "pedi; sepedi; sotho du Nord",
		},
		"NUB": {
			alph3b: "NUB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Nubian languages",
			frName: "nubiennes, langues",
		},
		"NWC": {
			alph3b: "NWC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Classical Newari; Old Newari; Classical Nepal Bhasa",
			frName: "newari classique",
		},
		"NYA": {
			alph3b: "NYA",
			alph3t: "XXX",
			alph2:  "NY",
			enName: "Chichewa; Chewa; Nyanja",
			frName: "chichewa; chewa; nyanja",
		},
		"NYM": {
			alph3b: "NYM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Nyamwezi",
			frName: "nyamwezi",
		},
		"NYN": {
			alph3b: "NYN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Nyankole",
			frName: "nyankolé",
		},
		"NYO": {
			alph3b: "NYO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Nyoro",
			frName: "nyoro",
		},
		"NZI": {
			alph3b: "NZI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Nzima",
			frName: "nzema",
		},
		"OCI": {
			alph3b: "OCI",
			alph3t: "XXX",
			alph2:  "OC",
			enName: "Occitan (post 1500)",
			frName: "occitan (après 1500)",
		},
		"OJI": {
			alph3b: "OJI",
			alph3t: "XXX",
			alph2:  "OJ",
			enName: "Ojibwa",
			frName: "ojibwa",
		},
		"ORI": {
			alph3b: "ORI",
			alph3t: "XXX",
			alph2:  "OR",
			enName: "Oriya",
			frName: "oriya",
		},
		"ORM": {
			alph3b: "ORM",
			alph3t: "XXX",
			alph2:  "OM",
			enName: "Oromo",
			frName: "galla",
		},
		"OSA": {
			alph3b: "OSA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Osage",
			frName: "osage",
		},
		"OSS": {
			alph3b: "OSS",
			alph3t: "XXX",
			alph2:  "OS",
			enName: "Ossetian; Ossetic",
			frName: "ossète",
		},
		"OTA": {
			alph3b: "OTA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Turkish, Ottoman (1500-1928)",
			frName: "turc ottoman (1500-1928)",
		},
		"OTO": {
			alph3b: "OTO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Otomian languages",
			frName: "otomi, langues",
		},
		"PAA": {
			alph3b: "PAA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Papuan languages",
			frName: "papoues, langues",
		},
		"PAG": {
			alph3b: "PAG",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Pangasinan",
			frName: "pangasinan",
		},
		"PAL": {
			alph3b: "PAL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Pahlavi",
			frName: "pahlavi",
		},
		"PAM": {
			alph3b: "PAM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Pampanga; Kapampangan",
			frName: "pampangan",
		},
		"PAN": {
			alph3b: "PAN",
			alph3t: "XXX",
			alph2:  "PA",
			enName: "Panjabi; Punjabi",
			frName: "pendjabi",
		},
		"PAP": {
			alph3b: "PAP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Papiamento",
			frName: "papiamento",
		},
		"PAU": {
			alph3b: "PAU",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Palauan",
			frName: "palau",
		},
		"PEO": {
			alph3b: "PEO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Persian, Old (ca.600-400 B.C.)",
			frName: "perse, vieux (ca. 600-400 av. J.-C.)",
		},
		"PER": {
			alph3b: "PER",
			alph3t: "FAS",
			alph2:  "FA",
			enName: "Persian",
			frName: "persan",
		},
		"PHI": {
			alph3b: "PHI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Philippine languages",
			frName: "philippines, langues",
		},
		"PHN": {
			alph3b: "PHN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Phoenician",
			frName: "phénicien",
		},
		"PLI": {
			alph3b: "PLI",
			alph3t: "XXX",
			alph2:  "PI",
			enName: "Pali",
			frName: "pali",
		},
		"POL": {
			alph3b: "POL",
			alph3t: "XXX",
			alph2:  "PL",
			enName: "Polish",
			frName: "polonais",
		},
		"PON": {
			alph3b: "PON",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Pohnpeian",
			frName: "pohnpei",
		},
		"POR": {
			alph3b: "POR",
			alph3t: "XXX",
			alph2:  "PT",
			enName: "Portuguese",
			frName: "portugais",
		},
		"PRA": {
			alph3b: "PRA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Prakrit languages",
			frName: "prâkrit, langues",
		},
		"PRO": {
			alph3b: "PRO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Provençal, Old (to 1500); Occitan, Old (to 1500)",
			frName: "provençal ancien (jusqu'à 1500); occitan ancien (jusqu'à 1500)",
		},
		"PUS": {
			alph3b: "PUS",
			alph3t: "XXX",
			alph2:  "PS",
			enName: "Pushto; Pashto",
			frName: "pachto",
		},
		"QAA-QTZ": {
			alph3b: "QAA-QTZ",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Reserved for local use",
			frName: "réservée à l'usage local",
		},
		"QUE": {
			alph3b: "QUE",
			alph3t: "XXX",
			alph2:  "QU",
			enName: "Quechua",
			frName: "quechua",
		},
		"RAJ": {
			alph3b: "RAJ",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Rajasthani",
			frName: "rajasthani",
		},
		"RAP": {
			alph3b: "RAP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Rapanui",
			frName: "rapanui",
		},
		"RAR": {
			alph3b: "RAR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Rarotongan; Cook Islands Maori",
			frName: "rarotonga; maori des îles Cook",
		},
		"ROA": {
			alph3b: "ROA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Romance languages",
			frName: "romanes, langues",
		},
		"ROH": {
			alph3b: "ROH",
			alph3t: "XXX",
			alph2:  "RM",
			enName: "Romansh",
			frName: "romanche",
		},
		"ROM": {
			alph3b: "ROM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Romany",
			frName: "tsigane",
		},
		"RUM": {
			alph3b: "RUM",
			alph3t: "RON",
			alph2:  "RO",
			enName: "Romanian; Moldavian; Moldovan",
			frName: "roumain; moldave",
		},
		"RUN": {
			alph3b: "RUN",
			alph3t: "XXX",
			alph2:  "RN",
			enName: "Rundi",
			frName: "rundi",
		},
		"RUP": {
			alph3b: "RUP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Aromanian; Arumanian; Macedo-Romanian",
			frName: "aroumain; macédo-roumain",
		},
		"RUS": {
			alph3b: "RUS",
			alph3t: "XXX",
			alph2:  "RU",
			enName: "Russian",
			frName: "russe",
		},
		"SAD": {
			alph3b: "SAD",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sandawe",
			frName: "sandawe",
		},
		"SAG": {
			alph3b: "SAG",
			alph3t: "XXX",
			alph2:  "SG",
			enName: "Sango",
			frName: "sango",
		},
		"SAH": {
			alph3b: "SAH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Yakut",
			frName: "iakoute",
		},
		"SAI": {
			alph3b: "SAI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "South American Indian languages",
			frName: "sud-amérindiennes, langues",
		},
		"SAL": {
			alph3b: "SAL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Salishan languages",
			frName: "salishennes, langues",
		},
		"SAM": {
			alph3b: "SAM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Samaritan Aramaic",
			frName: "samaritain",
		},
		"SAN": {
			alph3b: "SAN",
			alph3t: "XXX",
			alph2:  "SA",
			enName: "Sanskrit",
			frName: "sanskrit",
		},
		"SAS": {
			alph3b: "SAS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sasak",
			frName: "sasak",
		},
		"SAT": {
			alph3b: "SAT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Santali",
			frName: "santal",
		},
		"SCN": {
			alph3b: "SCN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sicilian",
			frName: "sicilien",
		},
		"SCO": {
			alph3b: "SCO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Scots",
			frName: "écossais",
		},
		"SEL": {
			alph3b: "SEL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Selkup",
			frName: "selkoupe",
		},
		"SEM": {
			alph3b: "SEM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Semitic languages",
			frName: "sémitiques, langues",
		},
		"SGA": {
			alph3b: "SGA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Irish, Old (to 900)",
			frName: "irlandais ancien (jusqu'à 900)",
		},
		"SGN": {
			alph3b: "SGN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sign Languages",
			frName: "langues des signes",
		},
		"SHN": {
			alph3b: "SHN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Shan",
			frName: "chan",
		},
		"SID": {
			alph3b: "SID",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sidamo",
			frName: "sidamo",
		},
		"SIN": {
			alph3b: "SIN",
			alph3t: "XXX",
			alph2:  "SI",
			enName: "Sinhala; Sinhalese",
			frName: "singhalais",
		},
		"SIO": {
			alph3b: "SIO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Siouan languages",
			frName: "sioux, langues",
		},
		"SIT": {
			alph3b: "SIT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sino-Tibetan languages",
			frName: "sino-tibétaines, langues",
		},
		"SLA": {
			alph3b: "SLA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Slavic languages",
			frName: "slaves, langues",
		},
		"SLO": {
			alph3b: "SLO",
			alph3t: "SLK",
			alph2:  "SK",
			enName: "Slovak",
			frName: "slovaque",
		},
		"SLV": {
			alph3b: "SLV",
			alph3t: "XXX",
			alph2:  "SL",
			enName: "Slovenian",
			frName: "slovène",
		},
		"SMA": {
			alph3b: "SMA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Southern Sami",
			frName: "sami du Sud",
		},
		"SME": {
			alph3b: "SME",
			alph3t: "XXX",
			alph2:  "SE",
			enName: "Northern Sami",
			frName: "sami du Nord",
		},
		"SMI": {
			alph3b: "SMI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sami languages",
			frName: "sames, langues",
		},
		"SMJ": {
			alph3b: "SMJ",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Lule Sami",
			frName: "sami de Lule",
		},
		"SMN": {
			alph3b: "SMN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Inari Sami",
			frName: "sami d'Inari",
		},
		"SMO": {
			alph3b: "SMO",
			alph3t: "XXX",
			alph2:  "SM",
			enName: "Samoan",
			frName: "samoan",
		},
		"SMS": {
			alph3b: "SMS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Skolt Sami",
			frName: "sami skolt",
		},
		"SNA": {
			alph3b: "SNA",
			alph3t: "XXX",
			alph2:  "SN",
			enName: "Shona",
			frName: "shona",
		},
		"SND": {
			alph3b: "SND",
			alph3t: "XXX",
			alph2:  "SD",
			enName: "Sindhi",
			frName: "sindhi",
		},
		"SNK": {
			alph3b: "SNK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Soninke",
			frName: "soninké",
		},
		"SOG": {
			alph3b: "SOG",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sogdian",
			frName: "sogdien",
		},
		"SOM": {
			alph3b: "SOM",
			alph3t: "XXX",
			alph2:  "SO",
			enName: "Somali",
			frName: "somali",
		},
		"SON": {
			alph3b: "SON",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Songhai languages",
			frName: "songhai, langues",
		},
		"SOT": {
			alph3b: "SOT",
			alph3t: "XXX",
			alph2:  "ST",
			enName: "Sotho, Southern",
			frName: "sotho du Sud",
		},
		"SPA": {
			alph3b: "SPA",
			alph3t: "XXX",
			alph2:  "ES",
			enName: "Spanish; Castilian",
			frName: "espagnol; castillan",
		},
		"SRD": {
			alph3b: "SRD",
			alph3t: "XXX",
			alph2:  "SC",
			enName: "Sardinian",
			frName: "sarde",
		},
		"SRN": {
			alph3b: "SRN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sranan Tongo",
			frName: "sranan tongo",
		},
		"SRP": {
			alph3b: "SRP",
			alph3t: "XXX",
			alph2:  "SR",
			enName: "Serbian",
			frName: "serbe",
		},
		"SRR": {
			alph3b: "SRR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Serer",
			frName: "sérère",
		},
		"SSA": {
			alph3b: "SSA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Nilo-Saharan languages",
			frName: "nilo-sahariennes, langues",
		},
		"SSW": {
			alph3b: "SSW",
			alph3t: "XXX",
			alph2:  "SS",
			enName: "Swati",
			frName: "swati",
		},
		"SUK": {
			alph3b: "SUK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sukuma",
			frName: "sukuma",
		},
		"SUN": {
			alph3b: "SUN",
			alph3t: "XXX",
			alph2:  "SU",
			enName: "Sundanese",
			frName: "soundanais",
		},
		"SUS": {
			alph3b: "SUS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Susu",
			frName: "soussou",
		},
		"SUX": {
			alph3b: "SUX",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sumerian",
			frName: "sumérien",
		},
		"SWA": {
			alph3b: "SWA",
			alph3t: "XXX",
			alph2:  "SW",
			enName: "Swahili",
			frName: "swahili",
		},
		"SWE": {
			alph3b: "SWE",
			alph3t: "XXX",
			alph2:  "SV",
			enName: "Swedish",
			frName: "suédois",
		},
		"SYC": {
			alph3b: "SYC",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Classical Syriac",
			frName: "syriaque classique",
		},
		"SYR": {
			alph3b: "SYR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Syriac",
			frName: "syriaque",
		},
		"TAH": {
			alph3b: "TAH",
			alph3t: "XXX",
			alph2:  "TY",
			enName: "Tahitian",
			frName: "tahitien",
		},
		"TAI": {
			alph3b: "TAI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tai languages",
			frName: "tai, langues",
		},
		"TAM": {
			alph3b: "TAM",
			alph3t: "XXX",
			alph2:  "TA",
			enName: "Tamil",
			frName: "tamoul",
		},
		"TAT": {
			alph3b: "TAT",
			alph3t: "XXX",
			alph2:  "TT",
			enName: "Tatar",
			frName: "tatar",
		},
		"TEL": {
			alph3b: "TEL",
			alph3t: "XXX",
			alph2:  "TE",
			enName: "Telugu",
			frName: "télougou",
		},
		"TEM": {
			alph3b: "TEM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Timne",
			frName: "temne",
		},
		"TER": {
			alph3b: "TER",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tereno",
			frName: "tereno",
		},
		"TET": {
			alph3b: "TET",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tetum",
			frName: "tetum",
		},
		"TGK": {
			alph3b: "TGK",
			alph3t: "XXX",
			alph2:  "TG",
			enName: "Tajik",
			frName: "tadjik",
		},
		"TGL": {
			alph3b: "TGL",
			alph3t: "XXX",
			alph2:  "TL",
			enName: "Tagalog",
			frName: "tagalog",
		},
		"THA": {
			alph3b: "THA",
			alph3t: "XXX",
			alph2:  "TH",
			enName: "Thai",
			frName: "thaï",
		},
		"TIB": {
			alph3b: "TIB",
			alph3t: "BOD",
			alph2:  "BO",
			enName: "Tibetan",
			frName: "tibétain",
		},
		"TIG": {
			alph3b: "TIG",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tigre",
			frName: "tigré",
		},
		"TIR": {
			alph3b: "TIR",
			alph3t: "XXX",
			alph2:  "TI",
			enName: "Tigrinya",
			frName: "tigrigna",
		},
		"TIV": {
			alph3b: "TIV",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tiv",
			frName: "tiv",
		},
		"TKL": {
			alph3b: "TKL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tokelau",
			frName: "tokelau",
		},
		"TLH": {
			alph3b: "TLH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Klingon; tlhIngan-Hol",
			frName: "klingon",
		},
		"TLI": {
			alph3b: "TLI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tlingit",
			frName: "tlingit",
		},
		"TMH": {
			alph3b: "TMH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tamashek",
			frName: "tamacheq",
		},
		"TOG": {
			alph3b: "TOG",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tonga (Nyasa)",
			frName: "tonga (Nyasa)",
		},
		"TON": {
			alph3b: "TON",
			alph3t: "XXX",
			alph2:  "TO",
			enName: "Tonga (Tonga Islands)",
			frName: "tongan (Îles Tonga)",
		},
		"TPI": {
			alph3b: "TPI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tok Pisin",
			frName: "tok pisin",
		},
		"TSI": {
			alph3b: "TSI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tsimshian",
			frName: "tsimshian",
		},
		"TSN": {
			alph3b: "TSN",
			alph3t: "XXX",
			alph2:  "TN",
			enName: "Tswana",
			frName: "tswana",
		},
		"TSO": {
			alph3b: "TSO",
			alph3t: "XXX",
			alph2:  "TS",
			enName: "Tsonga",
			frName: "tsonga",
		},
		"TUK": {
			alph3b: "TUK",
			alph3t: "XXX",
			alph2:  "TK",
			enName: "Turkmen",
			frName: "turkmène",
		},
		"TUM": {
			alph3b: "TUM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tumbuka",
			frName: "tumbuka",
		},
		"TUP": {
			alph3b: "TUP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tupi languages",
			frName: "tupi, langues",
		},
		"TUR": {
			alph3b: "TUR",
			alph3t: "XXX",
			alph2:  "TR",
			enName: "Turkish",
			frName: "turc",
		},
		"TUT": {
			alph3b: "TUT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Altaic languages",
			frName: "altaïques, langues",
		},
		"TVL": {
			alph3b: "TVL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tuvalu",
			frName: "tuvalu",
		},
		"TWI": {
			alph3b: "TWI",
			alph3t: "XXX",
			alph2:  "TW",
			enName: "Twi",
			frName: "twi",
		},
		"TYV": {
			alph3b: "TYV",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Tuvinian",
			frName: "touva",
		},
		"UDM": {
			alph3b: "UDM",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Udmurt",
			frName: "oudmourte",
		},
		"UGA": {
			alph3b: "UGA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Ugaritic",
			frName: "ougaritique",
		},
		"UIG": {
			alph3b: "UIG",
			alph3t: "XXX",
			alph2:  "UG",
			enName: "Uighur; Uyghur",
			frName: "ouïgour",
		},
		"UKR": {
			alph3b: "UKR",
			alph3t: "XXX",
			alph2:  "UK",
			enName: "Ukrainian",
			frName: "ukrainien",
		},
		"UMB": {
			alph3b: "UMB",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Umbundu",
			frName: "umbundu",
		},
		"UND": {
			alph3b: "UND",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Undetermined",
			frName: "indéterminée",
		},
		"URD": {
			alph3b: "URD",
			alph3t: "XXX",
			alph2:  "UR",
			enName: "Urdu",
			frName: "ourdou",
		},
		"UZB": {
			alph3b: "UZB",
			alph3t: "XXX",
			alph2:  "UZ",
			enName: "Uzbek",
			frName: "ouszbek",
		},
		"VAI": {
			alph3b: "VAI",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Vai",
			frName: "vaï",
		},
		"VEN": {
			alph3b: "VEN",
			alph3t: "XXX",
			alph2:  "VE",
			enName: "Venda",
			frName: "venda",
		},
		"VIE": {
			alph3b: "VIE",
			alph3t: "XXX",
			alph2:  "VI",
			enName: "Vietnamese",
			frName: "vietnamien",
		},
		"VOL": {
			alph3b: "VOL",
			alph3t: "XXX",
			alph2:  "VO",
			enName: "Volapük",
			frName: "volapük",
		},
		"VOT": {
			alph3b: "VOT",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Votic",
			frName: "vote",
		},
		"WAK": {
			alph3b: "WAK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Wakashan languages",
			frName: "wakashanes, langues",
		},
		"WAL": {
			alph3b: "WAL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Wolaitta; Wolaytta",
			frName: "wolaitta; wolaytta",
		},
		"WAR": {
			alph3b: "WAR",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Waray",
			frName: "waray",
		},
		"WAS": {
			alph3b: "WAS",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Washo",
			frName: "washo",
		},
		"WEL": {
			alph3b: "WEL",
			alph3t: "CYM",
			alph2:  "CY",
			enName: "Welsh",
			frName: "gallois",
		},
		"WEN": {
			alph3b: "WEN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Sorbian languages",
			frName: "sorabes, langues",
		},
		"WLN": {
			alph3b: "WLN",
			alph3t: "XXX",
			alph2:  "WA",
			enName: "Walloon",
			frName: "wallon",
		},
		"WOL": {
			alph3b: "WOL",
			alph3t: "XXX",
			alph2:  "WO",
			enName: "Wolof",
			frName: "wolof",
		},
		"XAL": {
			alph3b: "XAL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Kalmyk; Oirat",
			frName: "kalmouk; oïrat",
		},
		"XHO": {
			alph3b: "XHO",
			alph3t: "XXX",
			alph2:  "XH",
			enName: "Xhosa",
			frName: "xhosa",
		},
		"YAO": {
			alph3b: "YAO",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Yao",
			frName: "yao",
		},
		"YAP": {
			alph3b: "YAP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Yapese",
			frName: "yapois",
		},
		"YID": {
			alph3b: "YID",
			alph3t: "XXX",
			alph2:  "YI",
			enName: "Yiddish",
			frName: "yiddish",
		},
		"YOR": {
			alph3b: "YOR",
			alph3t: "XXX",
			alph2:  "YO",
			enName: "Yoruba",
			frName: "yoruba",
		},
		"YPK": {
			alph3b: "YPK",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Yupik languages",
			frName: "yupik, langues",
		},
		"ZAP": {
			alph3b: "ZAP",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Zapotec",
			frName: "zapotèque",
		},
		"ZBL": {
			alph3b: "ZBL",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Blissymbols; Blissymbolics; Bliss",
			frName: "symboles Bliss; Bliss",
		},
		"ZEN": {
			alph3b: "ZEN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Zenaga",
			frName: "zenaga",
		},
		"ZGH": {
			alph3b: "ZGH",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Standard Moroccan Tamazight",
			frName: "amazighe standard marocain",
		},
		"ZHA": {
			alph3b: "ZHA",
			alph3t: "XXX",
			alph2:  "ZA",
			enName: "Zhuang; Chuang",
			frName: "zhuang; chuang",
		},
		"ZND": {
			alph3b: "ZND",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Zande languages",
			frName: "zandé, langues",
		},
		"ZUL": {
			alph3b: "ZUL",
			alph3t: "XXX",
			alph2:  "ZU",
			enName: "Zulu",
			frName: "zoulou",
		},
		"ZUN": {
			alph3b: "ZUN",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Zuni",
			frName: "zuni",
		},
		"ZXX": {
			alph3b: "ZXX",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "No linguistic content; Not applicable",
			frName: "pas de contenu linguistique; non applicable",
		},
		"ZZA": {
			alph3b: "ZZA",
			alph3t: "XXX",
			alph2:  "XX",
			enName: "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
			frName: "zaza; dimili; dimli; kirdki; kirmanjki; zazaki",
		},
	}
)
