package iso639

var (
	isocodes2 = map[string]ISOEntry{
		"AA": {
			alph3b: "AAR",
			alph3t: "XXX",
			alph2:  "AA",
			enName: "Afar",
			frName: "afar",
		},
		"AB": {
			alph3b: "ABK",
			alph3t: "XXX",
			alph2:  "AB",
			enName: "Abkhazian",
			frName: "abkhaze",
		},
		"AF": {
			alph3b: "AFR",
			alph3t: "XXX",
			alph2:  "AF",
			enName: "Afrikaans",
			frName: "afrikaans",
		},
		"AK": {
			alph3b: "AKA",
			alph3t: "XXX",
			alph2:  "AK",
			enName: "Akan",
			frName: "akan",
		},
		"SQ": {
			alph3b: "ALB",
			alph3t: "SQI",
			alph2:  "SQ",
			enName: "Albanian",
			frName: "albanais",
		},
		"AM": {
			alph3b: "AMH",
			alph3t: "XXX",
			alph2:  "AM",
			enName: "Amharic",
			frName: "amharique",
		},
		"AR": {
			alph3b: "ARA",
			alph3t: "XXX",
			alph2:  "AR",
			enName: "Arabic",
			frName: "arabe",
		},
		"AN": {
			alph3b: "ARG",
			alph3t: "XXX",
			alph2:  "AN",
			enName: "Aragonese",
			frName: "aragonais",
		},
		"HY": {
			alph3b: "ARM",
			alph3t: "HYE",
			alph2:  "HY",
			enName: "Armenian",
			frName: "arménien",
		},
		"AS": {
			alph3b: "ASM",
			alph3t: "XXX",
			alph2:  "AS",
			enName: "Assamese",
			frName: "assamais",
		},
		"AV": {
			alph3b: "AVA",
			alph3t: "XXX",
			alph2:  "AV",
			enName: "Avaric",
			frName: "avar",
		},
		"AE": {
			alph3b: "AVE",
			alph3t: "XXX",
			alph2:  "AE",
			enName: "Avestan",
			frName: "avestique",
		},
		"AY": {
			alph3b: "AYM",
			alph3t: "XXX",
			alph2:  "AY",
			enName: "Aymara",
			frName: "aymara",
		},
		"AZ": {
			alph3b: "AZE",
			alph3t: "XXX",
			alph2:  "AZ",
			enName: "Azerbaijani",
			frName: "azéri",
		},
		"BA": {
			alph3b: "BAK",
			alph3t: "XXX",
			alph2:  "BA",
			enName: "Bashkir",
			frName: "bachkir",
		},
		"BM": {
			alph3b: "BAM",
			alph3t: "XXX",
			alph2:  "BM",
			enName: "Bambara",
			frName: "bambara",
		},
		"EU": {
			alph3b: "BAQ",
			alph3t: "EUS",
			alph2:  "EU",
			enName: "Basque",
			frName: "basque",
		},
		"BE": {
			alph3b: "BEL",
			alph3t: "XXX",
			alph2:  "BE",
			enName: "Belarusian",
			frName: "biélorusse",
		},
		"BN": {
			alph3b: "BEN",
			alph3t: "XXX",
			alph2:  "BN",
			enName: "Bengali",
			frName: "bengali",
		},
		"BH": {
			alph3b: "BIH",
			alph3t: "XXX",
			alph2:  "BH",
			enName: "Bihari languages",
			frName: "langues biharis",
		},
		"BI": {
			alph3b: "BIS",
			alph3t: "XXX",
			alph2:  "BI",
			enName: "Bislama",
			frName: "bichlamar",
		},
		"BS": {
			alph3b: "BOS",
			alph3t: "XXX",
			alph2:  "BS",
			enName: "Bosnian",
			frName: "bosniaque",
		},
		"BR": {
			alph3b: "BRE",
			alph3t: "XXX",
			alph2:  "BR",
			enName: "Breton",
			frName: "breton",
		},
		"BG": {
			alph3b: "BUL",
			alph3t: "XXX",
			alph2:  "BG",
			enName: "Bulgarian",
			frName: "bulgare",
		},
		"MY": {
			alph3b: "BUR",
			alph3t: "MYA",
			alph2:  "MY",
			enName: "Burmese",
			frName: "birman",
		},
		"CA": {
			alph3b: "CAT",
			alph3t: "XXX",
			alph2:  "CA",
			enName: "Catalan; Valencian",
			frName: "catalan; valencien",
		},
		"CH": {
			alph3b: "CHA",
			alph3t: "XXX",
			alph2:  "CH",
			enName: "Chamorro",
			frName: "chamorro",
		},
		"CE": {
			alph3b: "CHE",
			alph3t: "XXX",
			alph2:  "CE",
			enName: "Chechen",
			frName: "tchétchène",
		},
		"ZH": {
			alph3b: "CHI",
			alph3t: "ZHO",
			alph2:  "ZH",
			enName: "Chinese",
			frName: "chinois",
		},
		"CU": {
			alph3b: "CHU",
			alph3t: "XXX",
			alph2:  "CU",
			enName: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
			frName: "slavon d'église; vieux slave; slavon liturgique; vieux bulgare",
		},
		"CV": {
			alph3b: "CHV",
			alph3t: "XXX",
			alph2:  "CV",
			enName: "Chuvash",
			frName: "tchouvache",
		},
		"KW": {
			alph3b: "COR",
			alph3t: "XXX",
			alph2:  "KW",
			enName: "Cornish",
			frName: "cornique",
		},
		"CO": {
			alph3b: "COS",
			alph3t: "XXX",
			alph2:  "CO",
			enName: "Corsican",
			frName: "corse",
		},
		"CR": {
			alph3b: "CRE",
			alph3t: "XXX",
			alph2:  "CR",
			enName: "Cree",
			frName: "cree",
		},
		"CS": {
			alph3b: "CZE",
			alph3t: "CES",
			alph2:  "CS",
			enName: "Czech",
			frName: "tchèque",
		},
		"DA": {
			alph3b: "DAN",
			alph3t: "XXX",
			alph2:  "DA",
			enName: "Danish",
			frName: "danois",
		},
		"DV": {
			alph3b: "DIV",
			alph3t: "XXX",
			alph2:  "DV",
			enName: "Divehi; Dhivehi; Maldivian",
			frName: "maldivien",
		},
		"NL": {
			alph3b: "DUT",
			alph3t: "NLD",
			alph2:  "NL",
			enName: "Dutch; Flemish",
			frName: "néerlandais; flamand",
		},
		"DZ": {
			alph3b: "DZO",
			alph3t: "XXX",
			alph2:  "DZ",
			enName: "Dzongkha",
			frName: "dzongkha",
		},
		"EN": {
			alph3b: "ENG",
			alph3t: "XXX",
			alph2:  "EN",
			enName: "English",
			frName: "anglais",
		},
		"EO": {
			alph3b: "EPO",
			alph3t: "XXX",
			alph2:  "EO",
			enName: "Esperanto",
			frName: "espéranto",
		},
		"ET": {
			alph3b: "EST",
			alph3t: "XXX",
			alph2:  "ET",
			enName: "Estonian",
			frName: "estonien",
		},
		"EE": {
			alph3b: "EWE",
			alph3t: "XXX",
			alph2:  "EE",
			enName: "Ewe",
			frName: "éwé",
		},
		"FO": {
			alph3b: "FAO",
			alph3t: "XXX",
			alph2:  "FO",
			enName: "Faroese",
			frName: "féroïen",
		},
		"FJ": {
			alph3b: "FIJ",
			alph3t: "XXX",
			alph2:  "FJ",
			enName: "Fijian",
			frName: "fidjien",
		},
		"FI": {
			alph3b: "FIN",
			alph3t: "XXX",
			alph2:  "FI",
			enName: "Finnish",
			frName: "finnois",
		},
		"FR": {
			alph3b: "FRE",
			alph3t: "FRA",
			alph2:  "FR",
			enName: "French",
			frName: "français",
		},
		"FY": {
			alph3b: "FRY",
			alph3t: "XXX",
			alph2:  "FY",
			enName: "Western Frisian",
			frName: "frison occidental",
		},
		"FF": {
			alph3b: "FUL",
			alph3t: "XXX",
			alph2:  "FF",
			enName: "Fulah",
			frName: "peul",
		},
		"KA": {
			alph3b: "GEO",
			alph3t: "KAT",
			alph2:  "KA",
			enName: "Georgian",
			frName: "géorgien",
		},
		"DE": {
			alph3b: "GER",
			alph3t: "DEU",
			alph2:  "DE",
			enName: "German",
			frName: "allemand",
		},
		"GD": {
			alph3b: "GLA",
			alph3t: "XXX",
			alph2:  "GD",
			enName: "Gaelic; Scottish Gaelic",
			frName: "gaélique; gaélique écossais",
		},
		"GA": {
			alph3b: "GLE",
			alph3t: "XXX",
			alph2:  "GA",
			enName: "Irish",
			frName: "irlandais",
		},
		"GL": {
			alph3b: "GLG",
			alph3t: "XXX",
			alph2:  "GL",
			enName: "Galician",
			frName: "galicien",
		},
		"GV": {
			alph3b: "GLV",
			alph3t: "XXX",
			alph2:  "GV",
			enName: "Manx",
			frName: "manx; mannois",
		},
		"EL": {
			alph3b: "GRE",
			alph3t: "ELL",
			alph2:  "EL",
			enName: "Greek, Modern (1453-)",
			frName: "grec moderne (après 1453)",
		},
		"GN": {
			alph3b: "GRN",
			alph3t: "XXX",
			alph2:  "GN",
			enName: "Guarani",
			frName: "guarani",
		},
		"GU": {
			alph3b: "GUJ",
			alph3t: "XXX",
			alph2:  "GU",
			enName: "Gujarati",
			frName: "goudjrati",
		},
		"HT": {
			alph3b: "HAT",
			alph3t: "XXX",
			alph2:  "HT",
			enName: "Haitian; Haitian Creole",
			frName: "haïtien; créole haïtien",
		},
		"HA": {
			alph3b: "HAU",
			alph3t: "XXX",
			alph2:  "HA",
			enName: "Hausa",
			frName: "haoussa",
		},
		"HE": {
			alph3b: "HEB",
			alph3t: "XXX",
			alph2:  "HE",
			enName: "Hebrew",
			frName: "hébreu",
		},
		"HZ": {
			alph3b: "HER",
			alph3t: "XXX",
			alph2:  "HZ",
			enName: "Herero",
			frName: "herero",
		},
		"HI": {
			alph3b: "HIN",
			alph3t: "XXX",
			alph2:  "HI",
			enName: "Hindi",
			frName: "hindi",
		},
		"HO": {
			alph3b: "HMO",
			alph3t: "XXX",
			alph2:  "HO",
			enName: "Hiri Motu",
			frName: "hiri motu",
		},
		"HR": {
			alph3b: "HRV",
			alph3t: "XXX",
			alph2:  "HR",
			enName: "Croatian",
			frName: "croate",
		},
		"HU": {
			alph3b: "HUN",
			alph3t: "XXX",
			alph2:  "HU",
			enName: "Hungarian",
			frName: "hongrois",
		},
		"IG": {
			alph3b: "IBO",
			alph3t: "XXX",
			alph2:  "IG",
			enName: "Igbo",
			frName: "igbo",
		},
		"IS": {
			alph3b: "ICE",
			alph3t: "ISL",
			alph2:  "IS",
			enName: "Icelandic",
			frName: "islandais",
		},
		"IO": {
			alph3b: "IDO",
			alph3t: "XXX",
			alph2:  "IO",
			enName: "Ido",
			frName: "ido",
		},
		"II": {
			alph3b: "III",
			alph3t: "XXX",
			alph2:  "II",
			enName: "Sichuan Yi; Nuosu",
			frName: "yi de Sichuan",
		},
		"IU": {
			alph3b: "IKU",
			alph3t: "XXX",
			alph2:  "IU",
			enName: "Inuktitut",
			frName: "inuktitut",
		},
		"IE": {
			alph3b: "ILE",
			alph3t: "XXX",
			alph2:  "IE",
			enName: "Interlingue; Occidental",
			frName: "interlingue",
		},
		"IA": {
			alph3b: "INA",
			alph3t: "XXX",
			alph2:  "IA",
			enName: "Interlingua (International Auxiliary Language Association)",
			frName: "interlingua (langue auxiliaire internationale)",
		},
		"ID": {
			alph3b: "IND",
			alph3t: "XXX",
			alph2:  "ID",
			enName: "Indonesian",
			frName: "indonésien",
		},
		"IK": {
			alph3b: "IPK",
			alph3t: "XXX",
			alph2:  "IK",
			enName: "Inupiaq",
			frName: "inupiaq",
		},
		"IT": {
			alph3b: "ITA",
			alph3t: "XXX",
			alph2:  "IT",
			enName: "Italian",
			frName: "italien",
		},
		"JV": {
			alph3b: "JAV",
			alph3t: "XXX",
			alph2:  "JV",
			enName: "Javanese",
			frName: "javanais",
		},
		"JA": {
			alph3b: "JPN",
			alph3t: "XXX",
			alph2:  "JA",
			enName: "Japanese",
			frName: "japonais",
		},
		"KL": {
			alph3b: "KAL",
			alph3t: "XXX",
			alph2:  "KL",
			enName: "Kalaallisut; Greenlandic",
			frName: "groenlandais",
		},
		"KN": {
			alph3b: "KAN",
			alph3t: "XXX",
			alph2:  "KN",
			enName: "Kannada",
			frName: "kannada",
		},
		"KS": {
			alph3b: "KAS",
			alph3t: "XXX",
			alph2:  "KS",
			enName: "Kashmiri",
			frName: "kashmiri",
		},
		"KR": {
			alph3b: "KAU",
			alph3t: "XXX",
			alph2:  "KR",
			enName: "Kanuri",
			frName: "kanouri",
		},
		"KK": {
			alph3b: "KAZ",
			alph3t: "XXX",
			alph2:  "KK",
			enName: "Kazakh",
			frName: "kazakh",
		},
		"KM": {
			alph3b: "KHM",
			alph3t: "XXX",
			alph2:  "KM",
			enName: "Central Khmer",
			frName: "khmer central",
		},
		"KI": {
			alph3b: "KIK",
			alph3t: "XXX",
			alph2:  "KI",
			enName: "Kikuyu; Gikuyu",
			frName: "kikuyu",
		},
		"RW": {
			alph3b: "KIN",
			alph3t: "XXX",
			alph2:  "RW",
			enName: "Kinyarwanda",
			frName: "rwanda",
		},
		"KY": {
			alph3b: "KIR",
			alph3t: "XXX",
			alph2:  "KY",
			enName: "Kirghiz; Kyrgyz",
			frName: "kirghiz",
		},
		"KV": {
			alph3b: "KOM",
			alph3t: "XXX",
			alph2:  "KV",
			enName: "Komi",
			frName: "kom",
		},
		"KG": {
			alph3b: "KON",
			alph3t: "XXX",
			alph2:  "KG",
			enName: "Kongo",
			frName: "kongo",
		},
		"KO": {
			alph3b: "KOR",
			alph3t: "XXX",
			alph2:  "KO",
			enName: "Korean",
			frName: "coréen",
		},
		"KJ": {
			alph3b: "KUA",
			alph3t: "XXX",
			alph2:  "KJ",
			enName: "Kuanyama; Kwanyama",
			frName: "kuanyama; kwanyama",
		},
		"KU": {
			alph3b: "KUR",
			alph3t: "XXX",
			alph2:  "KU",
			enName: "Kurdish",
			frName: "kurde",
		},
		"LO": {
			alph3b: "LAO",
			alph3t: "XXX",
			alph2:  "LO",
			enName: "Lao",
			frName: "lao",
		},
		"LA": {
			alph3b: "LAT",
			alph3t: "XXX",
			alph2:  "LA",
			enName: "Latin",
			frName: "latin",
		},
		"LV": {
			alph3b: "LAV",
			alph3t: "XXX",
			alph2:  "LV",
			enName: "Latvian",
			frName: "letton",
		},
		"LI": {
			alph3b: "LIM",
			alph3t: "XXX",
			alph2:  "LI",
			enName: "Limburgan; Limburger; Limburgish",
			frName: "limbourgeois",
		},
		"LN": {
			alph3b: "LIN",
			alph3t: "XXX",
			alph2:  "LN",
			enName: "Lingala",
			frName: "lingala",
		},
		"LT": {
			alph3b: "LIT",
			alph3t: "XXX",
			alph2:  "LT",
			enName: "Lithuanian",
			frName: "lituanien",
		},
		"LB": {
			alph3b: "LTZ",
			alph3t: "XXX",
			alph2:  "LB",
			enName: "Luxembourgish; Letzeburgesch",
			frName: "luxembourgeois",
		},
		"LU": {
			alph3b: "LUB",
			alph3t: "XXX",
			alph2:  "LU",
			enName: "Luba-Katanga",
			frName: "luba-katanga",
		},
		"LG": {
			alph3b: "LUG",
			alph3t: "XXX",
			alph2:  "LG",
			enName: "Ganda",
			frName: "ganda",
		},
		"MK": {
			alph3b: "MAC",
			alph3t: "MKD",
			alph2:  "MK",
			enName: "Macedonian",
			frName: "macédonien",
		},
		"MH": {
			alph3b: "MAH",
			alph3t: "XXX",
			alph2:  "MH",
			enName: "Marshallese",
			frName: "marshall",
		},
		"ML": {
			alph3b: "MAL",
			alph3t: "XXX",
			alph2:  "ML",
			enName: "Malayalam",
			frName: "malayalam",
		},
		"MI": {
			alph3b: "MAO",
			alph3t: "MRI",
			alph2:  "MI",
			enName: "Maori",
			frName: "maori",
		},
		"MR": {
			alph3b: "MAR",
			alph3t: "XXX",
			alph2:  "MR",
			enName: "Marathi",
			frName: "marathe",
		},
		"MS": {
			alph3b: "MAY",
			alph3t: "MSA",
			alph2:  "MS",
			enName: "Malay",
			frName: "malais",
		},
		"MG": {
			alph3b: "MLG",
			alph3t: "XXX",
			alph2:  "MG",
			enName: "Malagasy",
			frName: "malgache",
		},
		"MT": {
			alph3b: "MLT",
			alph3t: "XXX",
			alph2:  "MT",
			enName: "Maltese",
			frName: "maltais",
		},
		"MN": {
			alph3b: "MON",
			alph3t: "XXX",
			alph2:  "MN",
			enName: "Mongolian",
			frName: "mongol",
		},
		"NA": {
			alph3b: "NAU",
			alph3t: "XXX",
			alph2:  "NA",
			enName: "Nauru",
			frName: "nauruan",
		},
		"NV": {
			alph3b: "NAV",
			alph3t: "XXX",
			alph2:  "NV",
			enName: "Navajo; Navaho",
			frName: "navaho",
		},
		"NR": {
			alph3b: "NBL",
			alph3t: "XXX",
			alph2:  "NR",
			enName: "Ndebele, South; South Ndebele",
			frName: "ndébélé du Sud",
		},
		"ND": {
			alph3b: "NDE",
			alph3t: "XXX",
			alph2:  "ND",
			enName: "Ndebele, North; North Ndebele",
			frName: "ndébélé du Nord",
		},
		"NG": {
			alph3b: "NDO",
			alph3t: "XXX",
			alph2:  "NG",
			enName: "Ndonga",
			frName: "ndonga",
		},
		"NE": {
			alph3b: "NEP",
			alph3t: "XXX",
			alph2:  "NE",
			enName: "Nepali",
			frName: "népalais",
		},
		"NN": {
			alph3b: "NNO",
			alph3t: "XXX",
			alph2:  "NN",
			enName: "Norwegian Nynorsk; Nynorsk, Norwegian",
			frName: "norvégien nynorsk; nynorsk, norvégien",
		},
		"NB": {
			alph3b: "NOB",
			alph3t: "XXX",
			alph2:  "NB",
			enName: "Bokmål, Norwegian; Norwegian Bokmål",
			frName: "norvégien bokmål",
		},
		"NO": {
			alph3b: "NOR",
			alph3t: "XXX",
			alph2:  "NO",
			enName: "Norwegian",
			frName: "norvégien",
		},
		"NY": {
			alph3b: "NYA",
			alph3t: "XXX",
			alph2:  "NY",
			enName: "Chichewa; Chewa; Nyanja",
			frName: "chichewa; chewa; nyanja",
		},
		"OC": {
			alph3b: "OCI",
			alph3t: "XXX",
			alph2:  "OC",
			enName: "Occitan (post 1500)",
			frName: "occitan (après 1500)",
		},
		"OJ": {
			alph3b: "OJI",
			alph3t: "XXX",
			alph2:  "OJ",
			enName: "Ojibwa",
			frName: "ojibwa",
		},
		"OR": {
			alph3b: "ORI",
			alph3t: "XXX",
			alph2:  "OR",
			enName: "Oriya",
			frName: "oriya",
		},
		"OM": {
			alph3b: "ORM",
			alph3t: "XXX",
			alph2:  "OM",
			enName: "Oromo",
			frName: "galla",
		},
		"OS": {
			alph3b: "OSS",
			alph3t: "XXX",
			alph2:  "OS",
			enName: "Ossetian; Ossetic",
			frName: "ossète",
		},
		"PA": {
			alph3b: "PAN",
			alph3t: "XXX",
			alph2:  "PA",
			enName: "Panjabi; Punjabi",
			frName: "pendjabi",
		},
		"FA": {
			alph3b: "PER",
			alph3t: "FAS",
			alph2:  "FA",
			enName: "Persian",
			frName: "persan",
		},
		"PI": {
			alph3b: "PLI",
			alph3t: "XXX",
			alph2:  "PI",
			enName: "Pali",
			frName: "pali",
		},
		"PL": {
			alph3b: "POL",
			alph3t: "XXX",
			alph2:  "PL",
			enName: "Polish",
			frName: "polonais",
		},
		"PT": {
			alph3b: "POR",
			alph3t: "XXX",
			alph2:  "PT",
			enName: "Portuguese",
			frName: "portugais",
		},
		"PS": {
			alph3b: "PUS",
			alph3t: "XXX",
			alph2:  "PS",
			enName: "Pushto; Pashto",
			frName: "pachto",
		},
		"QU": {
			alph3b: "QUE",
			alph3t: "XXX",
			alph2:  "QU",
			enName: "Quechua",
			frName: "quechua",
		},
		"RM": {
			alph3b: "ROH",
			alph3t: "XXX",
			alph2:  "RM",
			enName: "Romansh",
			frName: "romanche",
		},
		"RO": {
			alph3b: "RUM",
			alph3t: "RON",
			alph2:  "RO",
			enName: "Romanian; Moldavian; Moldovan",
			frName: "roumain; moldave",
		},
		"RN": {
			alph3b: "RUN",
			alph3t: "XXX",
			alph2:  "RN",
			enName: "Rundi",
			frName: "rundi",
		},
		"RU": {
			alph3b: "RUS",
			alph3t: "XXX",
			alph2:  "RU",
			enName: "Russian",
			frName: "russe",
		},
		"SG": {
			alph3b: "SAG",
			alph3t: "XXX",
			alph2:  "SG",
			enName: "Sango",
			frName: "sango",
		},
		"SA": {
			alph3b: "SAN",
			alph3t: "XXX",
			alph2:  "SA",
			enName: "Sanskrit",
			frName: "sanskrit",
		},
		"SI": {
			alph3b: "SIN",
			alph3t: "XXX",
			alph2:  "SI",
			enName: "Sinhala; Sinhalese",
			frName: "singhalais",
		},
		"SK": {
			alph3b: "SLO",
			alph3t: "SLK",
			alph2:  "SK",
			enName: "Slovak",
			frName: "slovaque",
		},
		"SL": {
			alph3b: "SLV",
			alph3t: "XXX",
			alph2:  "SL",
			enName: "Slovenian",
			frName: "slovène",
		},
		"SE": {
			alph3b: "SME",
			alph3t: "XXX",
			alph2:  "SE",
			enName: "Northern Sami",
			frName: "sami du Nord",
		},
		"SM": {
			alph3b: "SMO",
			alph3t: "XXX",
			alph2:  "SM",
			enName: "Samoan",
			frName: "samoan",
		},
		"SN": {
			alph3b: "SNA",
			alph3t: "XXX",
			alph2:  "SN",
			enName: "Shona",
			frName: "shona",
		},
		"SD": {
			alph3b: "SND",
			alph3t: "XXX",
			alph2:  "SD",
			enName: "Sindhi",
			frName: "sindhi",
		},
		"SO": {
			alph3b: "SOM",
			alph3t: "XXX",
			alph2:  "SO",
			enName: "Somali",
			frName: "somali",
		},
		"ST": {
			alph3b: "SOT",
			alph3t: "XXX",
			alph2:  "ST",
			enName: "Sotho, Southern",
			frName: "sotho du Sud",
		},
		"ES": {
			alph3b: "SPA",
			alph3t: "XXX",
			alph2:  "ES",
			enName: "Spanish; Castilian",
			frName: "espagnol; castillan",
		},
		"SC": {
			alph3b: "SRD",
			alph3t: "XXX",
			alph2:  "SC",
			enName: "Sardinian",
			frName: "sarde",
		},
		"SR": {
			alph3b: "SRP",
			alph3t: "XXX",
			alph2:  "SR",
			enName: "Serbian",
			frName: "serbe",
		},
		"SS": {
			alph3b: "SSW",
			alph3t: "XXX",
			alph2:  "SS",
			enName: "Swati",
			frName: "swati",
		},
		"SU": {
			alph3b: "SUN",
			alph3t: "XXX",
			alph2:  "SU",
			enName: "Sundanese",
			frName: "soundanais",
		},
		"SW": {
			alph3b: "SWA",
			alph3t: "XXX",
			alph2:  "SW",
			enName: "Swahili",
			frName: "swahili",
		},
		"SV": {
			alph3b: "SWE",
			alph3t: "XXX",
			alph2:  "SV",
			enName: "Swedish",
			frName: "suédois",
		},
		"TY": {
			alph3b: "TAH",
			alph3t: "XXX",
			alph2:  "TY",
			enName: "Tahitian",
			frName: "tahitien",
		},
		"TA": {
			alph3b: "TAM",
			alph3t: "XXX",
			alph2:  "TA",
			enName: "Tamil",
			frName: "tamoul",
		},
		"TT": {
			alph3b: "TAT",
			alph3t: "XXX",
			alph2:  "TT",
			enName: "Tatar",
			frName: "tatar",
		},
		"TE": {
			alph3b: "TEL",
			alph3t: "XXX",
			alph2:  "TE",
			enName: "Telugu",
			frName: "télougou",
		},
		"TG": {
			alph3b: "TGK",
			alph3t: "XXX",
			alph2:  "TG",
			enName: "Tajik",
			frName: "tadjik",
		},
		"TL": {
			alph3b: "TGL",
			alph3t: "XXX",
			alph2:  "TL",
			enName: "Tagalog",
			frName: "tagalog",
		},
		"TH": {
			alph3b: "THA",
			alph3t: "XXX",
			alph2:  "TH",
			enName: "Thai",
			frName: "thaï",
		},
		"BO": {
			alph3b: "TIB",
			alph3t: "BOD",
			alph2:  "BO",
			enName: "Tibetan",
			frName: "tibétain",
		},
		"TI": {
			alph3b: "TIR",
			alph3t: "XXX",
			alph2:  "TI",
			enName: "Tigrinya",
			frName: "tigrigna",
		},
		"TO": {
			alph3b: "TON",
			alph3t: "XXX",
			alph2:  "TO",
			enName: "Tonga (Tonga Islands)",
			frName: "tongan (Îles Tonga)",
		},
		"TN": {
			alph3b: "TSN",
			alph3t: "XXX",
			alph2:  "TN",
			enName: "Tswana",
			frName: "tswana",
		},
		"TS": {
			alph3b: "TSO",
			alph3t: "XXX",
			alph2:  "TS",
			enName: "Tsonga",
			frName: "tsonga",
		},
		"TK": {
			alph3b: "TUK",
			alph3t: "XXX",
			alph2:  "TK",
			enName: "Turkmen",
			frName: "turkmène",
		},
		"TR": {
			alph3b: "TUR",
			alph3t: "XXX",
			alph2:  "TR",
			enName: "Turkish",
			frName: "turc",
		},
		"TW": {
			alph3b: "TWI",
			alph3t: "XXX",
			alph2:  "TW",
			enName: "Twi",
			frName: "twi",
		},
		"UG": {
			alph3b: "UIG",
			alph3t: "XXX",
			alph2:  "UG",
			enName: "Uighur; Uyghur",
			frName: "ouïgour",
		},
		"UK": {
			alph3b: "UKR",
			alph3t: "XXX",
			alph2:  "UK",
			enName: "Ukrainian",
			frName: "ukrainien",
		},
		"UR": {
			alph3b: "URD",
			alph3t: "XXX",
			alph2:  "UR",
			enName: "Urdu",
			frName: "ourdou",
		},
		"UZ": {
			alph3b: "UZB",
			alph3t: "XXX",
			alph2:  "UZ",
			enName: "Uzbek",
			frName: "ouszbek",
		},
		"VE": {
			alph3b: "VEN",
			alph3t: "XXX",
			alph2:  "VE",
			enName: "Venda",
			frName: "venda",
		},
		"VI": {
			alph3b: "VIE",
			alph3t: "XXX",
			alph2:  "VI",
			enName: "Vietnamese",
			frName: "vietnamien",
		},
		"VO": {
			alph3b: "VOL",
			alph3t: "XXX",
			alph2:  "VO",
			enName: "Volapük",
			frName: "volapük",
		},
		"CY": {
			alph3b: "WEL",
			alph3t: "CYM",
			alph2:  "CY",
			enName: "Welsh",
			frName: "gallois",
		},
		"WA": {
			alph3b: "WLN",
			alph3t: "XXX",
			alph2:  "WA",
			enName: "Walloon",
			frName: "wallon",
		},
		"WO": {
			alph3b: "WOL",
			alph3t: "XXX",
			alph2:  "WO",
			enName: "Wolof",
			frName: "wolof",
		},
		"XH": {
			alph3b: "XHO",
			alph3t: "XXX",
			alph2:  "XH",
			enName: "Xhosa",
			frName: "xhosa",
		},
		"YI": {
			alph3b: "YID",
			alph3t: "XXX",
			alph2:  "YI",
			enName: "Yiddish",
			frName: "yiddish",
		},
		"YO": {
			alph3b: "YOR",
			alph3t: "XXX",
			alph2:  "YO",
			enName: "Yoruba",
			frName: "yoruba",
		},
		"ZA": {
			alph3b: "ZHA",
			alph3t: "XXX",
			alph2:  "ZA",
			enName: "Zhuang; Chuang",
			frName: "zhuang; chuang",
		},
		"ZU": {
			alph3b: "ZUL",
			alph3t: "XXX",
			alph2:  "ZU",
			enName: "Zulu",
			frName: "zoulou",
		},
	}
)
